# Generated by Django 4.1.1 on 2022-09-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_category_flower_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории растений', 'verbose_name_plural': 'Категории растений'},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['-name'], 'verbose_name': 'Разновидности растений', 'verbose_name_plural': 'Разновидности растений'},
        ),
        migrations.AlterField(
            model_name='flower',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flower.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y%m%d', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время добавления'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='время изменения'),
        ),
    ]
