# Generated by Django 4.1.1 on 2022-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_alter_category_options_alter_category_n_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='flower',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
